name: "Run with Cache"
description: "Execute shell commands with S3-compatible caching - skip execution if cache exists"
inputs:
  access-key:
    description: "S3-compatible access key (AWS Access Key ID, GCS HMAC Access ID, etc.)"
    required: true
  secret-key:
    description: "S3-compatible secret key (AWS Secret Access Key, GCS HMAC Secret, etc.)"
    required: true
  endpoint:
    description: "S3-compatible endpoint URL (e.g., https://storage.googleapis.com for GCS)"
    required: false
  region:
    description: "S3 region (e.g., us-east-1, auto)"
    required: false
    default: 'auto'
  run:
    description: "Command(s) to run"
    required: true
  shell:
    description: "Shell to use for running commands (bash, sh, pwsh, python, etc.)"
    required: false
    default: 'bash'
  working-directory:
    description: "Working directory for the command"
    required: false
    default: '.'
  cache-path:
    description: "S3-compatible path for cache marker (s3://bucket/path or gs://bucket/path)"
    required: true
  include-stdout:
    description: "Include stdout in cache and return it as output"
    required: false
    default: 'false'
outputs:
  cache-hit:
    description: "true if cache was found and command was skipped, false otherwise"
  stdout:
    description: "Standard output from command (cached or actual, only if include-stdout=true)"
runs:
  using: 'node20'
  main: '../../dist/apps/run-cache/main.js'
