name: "Run with Cache"
description: "Execute shell commands with caching support"
inputs:
  run:
    description: "Command(s) to run"
    required: true
  shell:
    description: "Shell to use for running commands (bash, sh, pwsh, python, etc.)"
    required: false
    default: 'bash'
  working-directory:
    description: "Working directory for the command"
    required: false
    default: '.'
  cache-path:
    description: "Cache path for storing/retrieving results in GCS"
    required: true
  ttl:
    description: "Time to live for cache in seconds"
    required: false
    default: '86400' # 24 hours default
outputs:
  cache-hit:
    description: "Indicates if the cache was hit"
  stdout:
    description: "Standard output from the command"
  stderr:
    description: "Standard error from the command"
  exit-code:
    description: "Exit code from the command"
runs:
  using: 'node20'
  main: '../../dist/apps/run-cache/main.js'