name: "Run with Cache"
description: "Execute shell commands with simple caching - skip execution if cache exists"
inputs:
  run:
    description: "Command(s) to run"
    required: true
  shell:
    description: "Shell to use for running commands (bash, sh, pwsh, python, etc.)"
    required: false
    default: 'bash'
  working-directory:
    description: "Working directory for the command"
    required: false
    default: '.'
  cache-path:
    description: "GCS path for cache marker (gs://bucket/path/to/cache)"
    required: true
outputs:
  cache-hit:
    description: "true if cache was found and command was skipped, false otherwise"
  exit-code:
    description: "Exit code from the command (0 if cache hit, actual exit code if executed)"
runs:
  using: 'node20'
  main: '../../dist/apps/run-cache/main.js'