name: 'Affected Targets'
description: 'Determines affected components and generates corresponding SHA, recommended image tags, and change status based on the provided rules.'
author: Leblanc Meneses
branding:
  icon: 'target'
  color: 'red'
inputs:
  rules:
    description: 'Defines rules in a DSL format specified in README.md.'
    required: false
    default: ''
  rules-file:
    description: 'Reference to file containing rules in a DSL format specified in README.md.'
    required: false
    default: ''
  recommended-imagetags-tag-format-whenchanged:
    description: 'The prefix to add to the image tag. <prefix>{sha|10}<suffix>'
    required: false
    default: ''
  recommended-imagetags-tag-format:
    description: 'The prefix to add to the image tag. <prefix>{sha|10}<suffix>'
    required: false
    default: ''
  recommended-imagetags-tag-remove-target:
    description: 'Should the target prefix be removed?'
    required: false
    default: ''
  recommended-imagetags-registry:
    description: 'The registry to add to all image tags.'
    required: false
    default: ''
  changed-files-output-file:
    description: 'Writes a file containing a JSON array of ChangedFile objects, where each object has a file name and its change status.'
    required: false
    default: ''
  verbose:
    description: 'Enable verbose logging. Use "true" or "false".'
    required: false
    default: 'false'
outputs:
  affected:
    description: 'A JSON array representing the projects that have changes, recommended_imagetags, and commit SHA.'
  affected_shas:
    description: 'A JSON object where the propery is the target and value is the sha1'
  affected_changes:
    description: 'A JSON object where the propery is the target and value is a boolean signifying if the target had changes'
  affected_recommended_imagetags:
    description: 'A JSON object where the propery is the target and value is a boolean signifying if the target had changes'
runs:
  using: 'node20'
  main: '../../dist/apps/affected/main/main.js'
